name: ntaloventi

on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Build the Docker image
      run: lscpu